name: "jest-coverage"
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: ls
      - run: ls ../
      - run: cat package.json
      - uses: actions/checkout@v2
      - name: install apt packages for headless-gl
        run: sudo apt-get install libxi-dev xvfb libgl1-mesa-dev
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./
          coverage-file: ./coverage/report.json
          test-script: xvfb-run --auto-servernum npm run test:coverage
