name: jest
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: npm install
      run: npm install
    - name: Run jest test
      run: npm test
    - name: Upload test coverage artifact
      uses: actions/upload-artifact@v1
      with:
        name: coverage
        path: coverage