name: "jest-coverage"
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./
          coverage-file: ./coverage/report.json
