name: "coverage"
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./packages/ore-three/
